# Generated by Django 4.2.16 on 2025-02-23 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_estoque_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.IntegerField(choices=[(1, 'Dinheiro'), (2, 'Credito'), (3, 'Debito'), (4, 'Pix'), (5, 'Ticket'), (6, 'Outra')])),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pgto', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateTimeField(editable=False)),
                ('chave_acesso', models.CharField(max_length=44, unique=True)),
                ('total_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('icms', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ipi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cofins', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impostos_totais', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.pedido')),
            ],
        ),
    ]
